//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U7MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressData
    {
        public int ID { get; set; }
        public int RegionId { get; set; }
        public int DistrictId { get; set; }
        public int CityId { get; set; }
        public int StreetId { get; set; }
    
        public virtual City City { get; set; }
        public virtual District District { get; set; }
        public virtual Region Region { get; set; }
        public virtual Street Street { get; set; }
    }
}
