//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U7MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public int ClubID { get; set; }
        public string ClubName { get; set; }
        public string ClubNumber { get; set; }
        public Nullable<int> ClubHeadID { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string PostBox { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
