//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U7MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembersPhone
    {
        public int ID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> PhoneTypeID { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual PhoneTypes PhoneTypes { get; set; }
    }
}
