//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U7MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberBreeds
    {
        public int ID { get; set; }
        public int MembersId { get; set; }
        public int BreedsId { get; set; }
        public System.DateTime RowCreated { get; set; }
    
        public virtual Breeds Breeds { get; set; }
        public virtual Members Members { get; set; }
    }
}
