//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U7MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool isActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
