//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U7MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabbits
    {
        public int RabbitId { get; set; }
        public int RabbitBreedId { get; set; }
        public int MemberId { get; set; }
        public System.DateTime RabbitBirthDay { get; set; }
        public string RabbitGender { get; set; }
        public string RabbitColor { get; set; }
        public float Weight { get; set; }
        public float Ears { get; set; }
        public int PhotoAlbumId { get; set; }
    }
}
