//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U7MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_RabbitBreedColorList
    {
        public int BreedId { get; set; }
        public string BreedName { get; set; }
        public int ColorId { get; set; }
        public string ColorName { get; set; }
        public Nullable<int> BreedsId { get; set; }
        public int IsSelected { get; set; }
    }
}
